# Generated by Django 2.0 on 2018-01-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['sorted_title']},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['sorted_full_name']},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['sorted_title']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['sorted_title']},
        ),
    ]
