# Generated by Django 2.1.1 on 2018-09-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_naming_and_sorting'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='next_play',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='can be played again'),
        ),
    ]
