# Generated by Django 2.2.2 on 2019-07-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_new_song_path_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='track_gain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='recommended replaygain adjustment'),
        ),
        migrations.AddField(
            model_name='store',
            name='track_peak',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='highest volume level in the track'),
        ),
    ]
